name: create diagram after changes

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate visualization
        uses: githubocto/repo-visualizer@v0.7.1
        with:
          should_push: false  # Zorgt ervoor dat het diagram niet wordt gecommit en gepusht
          artifact_name: diagram

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: diagram
          path: ./diagram.svg
